name: 'Pop Scan'
description: 'Runs the SCA scan in the repository.'

inputs:
  commit-long-sha:
    description: 'If given, git will checkout to this commit and ignore the branch.'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commit-long-sha }}

    - name: Detect Pop
      shell: bash
      run: >
        bash <(curl -s https://detect.synopsys.com/detect9.sh)
        --blackduck.url=$env:BLACKDUCK_URL
        --blackduck.api.token=$env:BLACKDUCK_API_TOKEN
        --blackduck.trust.cert=true
        --blackduck.offline.mode=true
        --detect.docker.passthrough.service.timeout=960000
        --blackduck.timeout=600 --detect.gradle.excluded.projects=common-test
        --detect.gradle.excluded.configurations=test*
        --detect.gradle.configuration.types.excluded=UNRESOLVED
        --detect.blackduck.signature.scanner.arguments=\"--exclude /gradle/ --exclude /src/test/resources/\"
        --detect.project.version.name=9.1.0 --detect.project.codelocation.unmap=false --detect.accuracy.required=NONE
