name: 'Setup Action'
description: 'Sets up Github And JDK'
runs:
  using: composite
  steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'