name: Post Merge Workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/java-11-setup

  integration:
    needs: setup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/integration

  pop:
    needs: setup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pop
