name: 'Jacoco'
description: 'Run Jacoco to generate a test coverage report.'

inputs:
  secret_token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - uses: ./.github/actions/java-11-setup

    - name: Add Jacoco Test Coverage
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/**/build/test-results/**/*.xml
        token: ${{ inputs.secret_token }}
