name: Pop Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  pop:
    runs-on: self-hosted
    steps:
      - name: DETECT_PROJECT_VERSION_NAME_OVERRIDE
        run: |
          $DETECT_PROJECT_VERSION_NAME_OVERRIDE = '9.1.0'

      - name: Detect
        run: |
          pushd \\wsl.localhost\Ubuntu-20.04\home\basim\synopsys-detect
          bash pop.sh
          popd
