name: 'Remove Snapshot'
description: 'Removes `-SNAPSHOT` from project version.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup

    - name: Checking snapshot dependencies
      shell: bash
      run: |
        ./gradlew dependencies -q --configuration implementation

    - name: Current Version
      shell: bash
      run: |
        ./gradlew properties -q | grep '^version: '

    - name: Updating Version
      shell: bash
      run: |
        ./gradlew qaJaloja

    - name: New Version
      id: new_version
      shell: bash
      run: |
        echo "PROJ_VER=$(./gradlew properties -q | grep -oP '^version: \K.*')" >> $GITHUB_OUTPUT
        echo ${{ steps.new_version.outputs.PROJ_VER }}

    - uses: EndBug/add-and-commit@v9
      with:
        add: '.'

        default_author: github_actions
        message: Release ${{ steps.new_version.outputs.PROJ_VER }}

        pathspec_error_handling: ignore
        push: true
