name: Post Merge Actions

on:
  workflow_call:

permissions:
  contents: read

jobs:
  integration:
    runs-on: self-hosted
    steps:
      - name: Build with Gradle
        run: ./gradlew clean build -Ptags=integration
