name: Pop Scan

on:
  workflow_run:
    workflows: [ "Post Merge Workflow" ]
    branches:
      - master
      - '[0-9]+.[0-9]+.z'
      - '[0-9]+.[0-9]+.0'
    types:
      - completed

jobs:
  pop:
    runs-on: [ self-hosted, linux ]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pop
        with:
          commit-long-sha: ${{ github.ref }}
        env:
          BLACKDUCK_URL: ${{ vars.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
