name: Post Merge Workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  jdk-git-setup:
    uses: ./.github/workflows/sub-workflows/integration.yml
  pop:
    uses: ./.github/workflows/sub-workflows/pop.yml
  integration:
    uses: ./.github/workflows/sub-workflows/integration.yml
