name: Post Merge Workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  jdk-git-setup:
    uses: ./.github/actions/jdk-git-setup.yml
  pop:
    uses: ./.github/actions/pop.yml
  integration:
    uses: ./.github/actions/integration.yml
