name: Post Merge Workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  jdk-git-setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/integration.yml
  pop:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pop.yml
  integration:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/integration.yml
