# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Pre-merge workflow

on:
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+.z'
      - '[0-9]+.[0-9]+.0'
    types: [ 'opened', 'edited', 'reopened', 'synchronize', 'ready_for_review' ]

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

        # Setting up JDK 11 could be time-consuming for self-hosted runner
        # depending on the internet speed of the machine
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run battery, unit, and functional tests
        run: |
          ./gradlew clean build -Ptags="battery,unit,functional" -PpullReqNum="${{github.event.number}}" artifactoryPublish
