# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Pre-merge workflow

on:
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+.z'
      - '[0-9]+.[0-9]+.0'
    types: [ 'opened', 'edited', 'reopened', 'synchronize', 'ready_for_review' ]

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: .github/actions/java-11-setup

      - name: Build and run battery, unit, and functional tests
        run: |
          ./gradlew clean build -Ptags="battery,unit,functional" -PpullReqNum="${{github.event.number}}" artifactoryPublish
